# coding: utf-8

"""
    GobiSwitch

    GobiSwitch REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Status44dEnum(str, Enum):
    """
    * `CREATED` - Created * `PAYIN_VALIDATED` - Payin validated * `WRITE_BLOCKCHAIN` - Write blockchain * `PAYOUT_ORDERED` - Payout ordered * `PAYOUT_DONE` - Payout done * `FAILED` - Failed * `CANCELLED` - Cancelled
    """

    """
    allowed enum values
    """
    CREATED = 'CREATED'
    PAYIN_VALIDATED = 'PAYIN_VALIDATED'
    WRITE_BLOCKCHAIN = 'WRITE_BLOCKCHAIN'
    PAYOUT_ORDERED = 'PAYOUT_ORDERED'
    PAYOUT_DONE = 'PAYOUT_DONE'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Status44dEnum from a JSON string"""
        return cls(json.loads(json_str))


