# coding: utf-8

"""
    GobiSwitch

    GobiSwitch REST API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from openapi_client.models.organization_for_transaction import OrganizationForTransaction
from openapi_client.models.service_for_transaction import ServiceForTransaction
from openapi_client.models.status44d_enum import Status44dEnum
from typing import Optional, Set
from typing_extensions import Self

class TransactionCreate(BaseModel):
    """
    TransactionCreate
    """ # noqa: E501
    from_org: OrganizationForTransaction
    to_org: OrganizationForTransaction
    service: ServiceForTransaction
    uuid: UUID
    from_amount_from_currency: Annotated[str, Field(strict=True)]
    from_amount_to_currency: Annotated[str, Field(strict=True)]
    from_amount_usd: Annotated[str, Field(strict=True)]
    to_amount_from_currency: Annotated[str, Field(strict=True)]
    to_amount_to_currency: Annotated[str, Field(strict=True)]
    to_amount_usd: Annotated[str, Field(strict=True)]
    is_direct_convert: Optional[StrictBool] = None
    rate_from_to: Annotated[str, Field(strict=True)]
    rate_to_from: Annotated[str, Field(strict=True)]
    rate_from_currency_to_usd: Annotated[str, Field(strict=True)]
    rate_to_currency_to_usd: Annotated[str, Field(strict=True)]
    created_at: datetime
    updated_at: datetime
    arguments: Optional[Any] = None
    status: Status44dEnum
    blockchain_tx_id: Optional[StrictStr]
    from_currency_earnings: StrictInt
    to_currency_earnings: StrictInt
    usd_earnings: StrictInt
    __properties: ClassVar[List[str]] = ["from_org", "to_org", "service", "uuid", "from_amount_from_currency", "from_amount_to_currency", "from_amount_usd", "to_amount_from_currency", "to_amount_to_currency", "to_amount_usd", "is_direct_convert", "rate_from_to", "rate_to_from", "rate_from_currency_to_usd", "rate_to_currency_to_usd", "created_at", "updated_at", "arguments", "status", "blockchain_tx_id", "from_currency_earnings", "to_currency_earnings", "usd_earnings"]

    @field_validator('from_amount_from_currency')
    def from_amount_from_currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('from_amount_to_currency')
    def from_amount_to_currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('from_amount_usd')
    def from_amount_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('to_amount_from_currency')
    def to_amount_from_currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('to_amount_to_currency')
    def to_amount_to_currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('to_amount_usd')
    def to_amount_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('rate_from_to')
    def rate_from_to_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('rate_to_from')
    def rate_to_from_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('rate_from_currency_to_usd')
    def rate_from_currency_to_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    @field_validator('rate_to_currency_to_usd')
    def rate_to_currency_to_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,24}(?:\.\d{0,8})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,24}(?:\.\d{0,8})?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "from_org",
            "to_org",
            "service",
            "uuid",
            "from_amount_from_currency",
            "from_amount_to_currency",
            "from_amount_usd",
            "to_amount_from_currency",
            "to_amount_to_currency",
            "to_amount_usd",
            "rate_from_to",
            "rate_to_from",
            "rate_from_currency_to_usd",
            "rate_to_currency_to_usd",
            "created_at",
            "updated_at",
            "status",
            "blockchain_tx_id",
            "from_currency_earnings",
            "to_currency_earnings",
            "usd_earnings",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_org
        if self.from_org:
            _dict['from_org'] = self.from_org.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_org
        if self.to_org:
            _dict['to_org'] = self.to_org.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        # set to None if arguments (nullable) is None
        # and model_fields_set contains the field
        if self.arguments is None and "arguments" in self.model_fields_set:
            _dict['arguments'] = None

        # set to None if blockchain_tx_id (nullable) is None
        # and model_fields_set contains the field
        if self.blockchain_tx_id is None and "blockchain_tx_id" in self.model_fields_set:
            _dict['blockchain_tx_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from_org": OrganizationForTransaction.from_dict(obj["from_org"]) if obj.get("from_org") is not None else None,
            "to_org": OrganizationForTransaction.from_dict(obj["to_org"]) if obj.get("to_org") is not None else None,
            "service": ServiceForTransaction.from_dict(obj["service"]) if obj.get("service") is not None else None,
            "uuid": obj.get("uuid"),
            "from_amount_from_currency": obj.get("from_amount_from_currency"),
            "from_amount_to_currency": obj.get("from_amount_to_currency"),
            "from_amount_usd": obj.get("from_amount_usd"),
            "to_amount_from_currency": obj.get("to_amount_from_currency"),
            "to_amount_to_currency": obj.get("to_amount_to_currency"),
            "to_amount_usd": obj.get("to_amount_usd"),
            "is_direct_convert": obj.get("is_direct_convert"),
            "rate_from_to": obj.get("rate_from_to"),
            "rate_to_from": obj.get("rate_to_from"),
            "rate_from_currency_to_usd": obj.get("rate_from_currency_to_usd"),
            "rate_to_currency_to_usd": obj.get("rate_to_currency_to_usd"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "arguments": obj.get("arguments"),
            "status": obj.get("status"),
            "blockchain_tx_id": obj.get("blockchain_tx_id"),
            "from_currency_earnings": obj.get("from_currency_earnings"),
            "to_currency_earnings": obj.get("to_currency_earnings"),
            "usd_earnings": obj.get("usd_earnings")
        })
        return _obj


